---
- name: installing multiple packages
  hosts: webservers
  become: true
  tasks:
  - name: add a list of users
    user: name='{{ item }}' state=present
    with_items:
      - Raj
      - Sai
      - Hari

