---
- name: installing httpd and starting service
  hosts: webservers
  become: true
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: installed

  - name: starting service
    service:
      name: httpd
      state: started
