---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Ubuntu
    yum:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz
      dest: /opt

  - name: extract tar.gz file
    unarchive:
      src: /opt/apache-tomcat-8.5.96.tar.gz
      dest: /opt
      remote_src: True

  - name: change permissions of file
    file:
      path: /opt/apache-tomcat-8.5.96/bin/startup.sh
      mode: 0777

  - name: starting tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.96/bin


