---
- name: stopping service and uninstalling package
  hosts: webservers
  become: true
  tasks:
    - name: stopping the httpd service
      service:
        name: httpd
        state: stopped

    - name: uninstalling httpd
      yum:
        name: httpd
        state: removed
